# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestWawancara():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_wawancara(self):
    # Test name: Wawancara
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://pelayanan.kesbangpol.bandung.go.id/")
    # 2 | setWindowSize | 1552x880 | 
    self.driver.set_window_size(1552, 880)
    # 3 | click | css=a:nth-child(2) .chakra-text | 
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(2) .chakra-text").click()
    # 4 | runScript | window.scrollTo(0,411.61065673828125) | 
    self.driver.execute_script("window.scrollTo(0,411.61065673828125)")
    # 5 | click | id=nama | 
    self.driver.find_element(By.ID, "nama").click()
    # 6 | type | id=nama | Joko
    self.driver.find_element(By.ID, "nama").send_keys("Joko")
    # 7 | type | id=alamat | Jalan Swadaya
    self.driver.find_element(By.ID, "alamat").send_keys("Jalan Swadaya")
    # 8 | click | id=no_identitas | 
    self.driver.find_element(By.ID, "no_identitas").click()
    # 9 | type | id=no_identitas | 123
    self.driver.find_element(By.ID, "no_identitas").send_keys("123")
    # 10 | click | id=tujuan_dinas | 
    self.driver.find_element(By.ID, "tujuan_dinas").click()
    # 11 | type | id=tujuan_dinas | Dasa
    self.driver.find_element(By.ID, "tujuan_dinas").send_keys("Dasa")
    # 12 | click | id=judul_data | 
    self.driver.find_element(By.ID, "judul_data").click()
    # 13 | type | id=judul_data | DSA
    self.driver.find_element(By.ID, "judul_data").send_keys("DSA")
    # 14 | click | id=anggota | 
    self.driver.find_element(By.ID, "anggota").click()
    # 15 | type | id=anggota | SDA
    self.driver.find_element(By.ID, "anggota").send_keys("SDA")
    # 16 | click | id=jabatan | 
    self.driver.find_element(By.ID, "jabatan").click()
    # 17 | select | id=jabatan | label=Ketua Peneliti
    dropdown = self.driver.find_element(By.ID, "jabatan")
    dropdown.find_element(By.XPATH, "//option[. = 'Ketua Peneliti']").click()
    # 18 | click | id=nama_kampus | 
    self.driver.find_element(By.ID, "nama_kampus").click()
    # 19 | type | id=nama_kampus | DSA
    self.driver.find_element(By.ID, "nama_kampus").send_keys("DSA")
    # 20 | click | id=no_surat_kampus | 
    self.driver.find_element(By.ID, "no_surat_kampus").click()
    # 21 | type | id=no_surat_kampus | dSA
    self.driver.find_element(By.ID, "no_surat_kampus").send_keys("dSA")
    # 22 | click | id=tanggal_surat_kampus | 
    self.driver.find_element(By.ID, "tanggal_surat_kampus").click()
    # 23 | click | id=tanggal_surat_kampus | 
    self.driver.find_element(By.ID, "tanggal_surat_kampus").click()
    # 24 | type | id=tanggal_surat_kampus | 2023-09-10
    self.driver.find_element(By.ID, "tanggal_surat_kampus").send_keys("2023-09-10")
    # 25 | click | id=no_hp | 
    self.driver.find_element(By.ID, "no_hp").click()
    # 26 | type | id=no_hp | dwqdqwqdw
    self.driver.find_element(By.ID, "no_hp").send_keys("dwqdqwqdw")
    # 27 | click | css=.chakra-stack:nth-child(1) > .chakra-form-control:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".chakra-stack:nth-child(1) > .chakra-form-control:nth-child(1)").click()
    # 28 | click | id=attach_ktp | 
    self.driver.find_element(By.ID, "attach_ktp").click()
    # 29 | type | id=attach_ktp | C:\fakepath\catatan.txt
    self.driver.find_element(By.ID, "attach_ktp").send_keys("C:\\fakepath\\catatan.txt")
    # 30 | click | id=attach_suratKampus | 
    self.driver.find_element(By.ID, "attach_suratKampus").click()
    # 31 | type | id=attach_suratKampus | C:\fakepath\catatan.txt
    self.driver.find_element(By.ID, "attach_suratKampus").send_keys("C:\\fakepath\\catatan.txt")
    # 32 | click | id=attach_ktm | 
    self.driver.find_element(By.ID, "attach_ktm").click()
    # 33 | type | id=attach_ktm | C:\fakepath\catatan.txt
    self.driver.find_element(By.ID, "attach_ktm").send_keys("C:\\fakepath\\catatan.txt")
    # 34 | click | id=attach_vaksin | 
    self.driver.find_element(By.ID, "attach_vaksin").click()
    # 35 | type | id=attach_vaksin | C:\fakepath\catatan.txt
    self.driver.find_element(By.ID, "attach_vaksin").send_keys("C:\\fakepath\\catatan.txt")
    # 36 | click | id=attach_pasFoto | 
    self.driver.find_element(By.ID, "attach_pasFoto").click()
    # 37 | type | id=attach_pasFoto | C:\fakepath\catatan.txt
    self.driver.find_element(By.ID, "attach_pasFoto").send_keys("C:\\fakepath\\catatan.txt")
    # 38 | click | id=tombolKirim | 
    self.driver.find_element(By.ID, "tombolKirim").click()
    # 39 | mouseOver | id=tombolKirim | 
    element = self.driver.find_element(By.ID, "tombolKirim")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 40 | mouseOut | id=tombolKirim | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 41 | verifyElementPresent | css=.chakra-alert__title | 
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".chakra-alert__title")
    assert len(elements) > 0
  
