# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFooterTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_footerTest(self):
    # Test name: Footer Test
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://pelayanan.kesbangpol.bandung.go.id/")
    # 2 | setWindowSize | 1536x864 | 
    self.driver.set_window_size(1536, 864)
    # 3 | click | css=.chakra-stack:nth-child(2) > a:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".chakra-stack:nth-child(2) > a:nth-child(2)").click()
    # 4 | runScript | window.scrollTo(0,506.47039794921875) | 
    self.driver.execute_script("window.scrollTo(0,506.47039794921875)")
    # 5 | click | linkText=Penelitian | 
    self.driver.find_element(By.LINK_TEXT, "Penelitian").click()
    # 6 | runScript | window.scrollTo(0,445.298828125) | 
    self.driver.execute_script("window.scrollTo(0,445.298828125)")
    # 7 | click | css=.css-1h4ws66:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".css-1h4ws66:nth-child(2)").click()
    # 8 | click | linkText=Data/Wawancara | 
    self.driver.find_element(By.LINK_TEXT, "Data/Wawancara").click()
    # 9 | runScript | window.scrollTo(0,481.3304748535156) | 
    self.driver.execute_script("window.scrollTo(0,481.3304748535156)")
    # 10 | click | linkText=PKL/Magang/KKN | 
    self.driver.find_element(By.LINK_TEXT, "PKL/Magang/KKN").click()
    # 11 | runScript | window.scrollTo(0,420.7821350097656) | 
    self.driver.execute_script("window.scrollTo(0,420.7821350097656)")
    # 12 | click | css=a:nth-child(6) | 
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(6)").click()
    # 13 | click | css=.chakra-link:nth-child(2) > .chakra-button | 
    self.vars["window_handles"] = self.driver.window_handles
    # 14 | storeWindowHandle | root | 
    self.driver.find_element(By.CSS_SELECTOR, ".chakra-link:nth-child(2) > .chakra-button").click()
    # 15 | selectWindow | handle=${win3796} | 
    self.vars["win3796"] = self.wait_for_window(2000)
    # 16 | selectWindow | handle=${root} | 
    self.vars["root"] = self.driver.current_window_handle
    # 17 | click | css=.chakra-link:nth-child(3) > .chakra-button | 
    self.driver.switch_to.window(self.vars["win3796"])
    # 18 | selectWindow | handle=${win9437} | 
    self.driver.switch_to.window(self.vars["root"])
    # 19 | selectWindow | handle=${root} | 
    self.vars["window_handles"] = self.driver.window_handles
    # 20 | click | css=.css-hyb7bs:nth-child(1) > svg | 
    self.driver.find_element(By.CSS_SELECTOR, ".chakra-link:nth-child(3) > .chakra-button").click()
    # 21 | open | / | 
    self.vars["win9437"] = self.wait_for_window(2000)
    # 22 | click | css=.css-hyb7bs:nth-child(2) path | 
    self.driver.switch_to.window(self.vars["win9437"])
    # 23 | runScript | window.scrollTo(0,1020.7999877929688) | 
    self.driver.switch_to.window(self.vars["root"])
    # 24 | open | / | 
    self.driver.find_element(By.CSS_SELECTOR, ".css-hyb7bs:nth-child(1) > svg").click()
    # 25 | click | css=.css-hyb7bs:nth-child(3) path | 
    self.driver.get("https://pelayanan.kesbangpol.bandung.go.id/")
    self.driver.find_element(By.CSS_SELECTOR, ".css-hyb7bs:nth-child(2) path").click()
    self.driver.execute_script("window.scrollTo(0,1020.7999877929688)")
    self.driver.get("https://pelayanan.kesbangpol.bandung.go.id/")
    self.driver.find_element(By.CSS_SELECTOR, ".css-hyb7bs:nth-child(3) path").click()
  
