# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestHeaderTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_headerTest(self):
    # Test name: Header Test
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://pelayanan.kesbangpol.bandung.go.id/")
    # 2 | click | id=popover-trigger-:r2: | 
    self.driver.find_element(By.ID, "popover-trigger-:r2:").click()
    # 3 | setWindowSize | 1552x880 | 
    self.driver.set_window_size(1552, 880)
    # 4 | click | id=popover-trigger-:r4: | 
    self.driver.find_element(By.ID, "popover-trigger-:r4:").click()
    # 5 | click | css=a:nth-child(1) > .chakra-stack .chakra-text | 
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(1) > .chakra-stack .chakra-text").click()
    # 6 | click | id=popover-trigger-:r4: | 
    self.driver.find_element(By.ID, "popover-trigger-:r4:").click()
    # 7 | click | css=a:nth-child(2) .chakra-text | 
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(2) .chakra-text").click()
    # 8 | click | css=.css-yozxlk | 
    self.driver.find_element(By.CSS_SELECTOR, ".css-yozxlk").click()
    # 9 | click | id=popover-trigger-:r4: | 
    self.driver.find_element(By.ID, "popover-trigger-:r4:").click()
    # 10 | click | css=a:nth-child(3) .chakra-text | 
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(3) .chakra-text").click()
    # 11 | click | id=popover-trigger-:r6: | 
    self.driver.find_element(By.ID, "popover-trigger-:r6:").click()
    # 12 | click | css=.css-ankmtx | 
    self.driver.find_element(By.CSS_SELECTOR, ".css-ankmtx").click()
    # 13 | click | css=.css-16h2qf1 | 
    self.driver.find_element(By.CSS_SELECTOR, ".css-16h2qf1").click()
    # 14 | click | css=.css-1f91msi > .css-mcpu91 | 
    self.driver.find_element(By.CSS_SELECTOR, ".css-1f91msi > .css-mcpu91").click()
  
