# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFormPenelitian():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_formPenelitian(self):
    # Test name: Form Penelitian
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://pelayanan.kesbangpol.bandung.go.id/")
    # 2 | setWindowSize | 1536x864 | 
    self.driver.set_window_size(1536, 864)
    # 3 | click | id=popover-trigger-:r4: | 
    self.driver.find_element(By.ID, "popover-trigger-:r4:").click()
    # 4 | click | css=a:nth-child(1) > .chakra-stack .chakra-text | 
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(1) > .chakra-stack .chakra-text").click()
    # 5 | runScript | window.scrollTo(0,411.9947814941406) | 
    self.driver.execute_script("window.scrollTo(0,411.9947814941406)")
    # 6 | click | id=nama | 
    self.driver.find_element(By.ID, "nama").click()
    # 7 | type | id=nama | Siti
    self.driver.find_element(By.ID, "nama").send_keys("Siti")
    # 8 | click | id=alamat | 
    self.driver.find_element(By.ID, "alamat").click()
    # 9 | type | id=alamat | Jl pemuda 1
    self.driver.find_element(By.ID, "alamat").send_keys("Jl pemuda 1")
    # 10 | click | id=no_identitas | 
    self.driver.find_element(By.ID, "no_identitas").click()
    # 11 | type | id=no_identitas | 213098329801
    self.driver.find_element(By.ID, "no_identitas").send_keys("213098329801")
    # 12 | click | id=tujuan_dinas | 
    self.driver.find_element(By.ID, "tujuan_dinas").click()
    # 13 | type | id=tujuan_dinas | KOKOK
    self.driver.find_element(By.ID, "tujuan_dinas").send_keys("KOKOK")
    # 14 | click | id=anggota | 
    self.driver.find_element(By.ID, "anggota").click()
    # 15 | type | id=anggota | Riski
    self.driver.find_element(By.ID, "anggota").send_keys("Riski")
    # 16 | click | id=jabatan | 
    self.driver.find_element(By.ID, "jabatan").click()
    # 17 | select | id=jabatan | label=Ketua Peneliti
    dropdown = self.driver.find_element(By.ID, "jabatan")
    dropdown.find_element(By.XPATH, "//option[. = 'Ketua Peneliti']").click()
    # 18 | click | id=nama_kampus | 
    self.driver.find_element(By.ID, "nama_kampus").click()
    # 19 | type | id=nama_kampus | PT mencari Cinta Sejati
    self.driver.find_element(By.ID, "nama_kampus").send_keys("PT mencari Cinta Sejati")
    # 20 | click | id=no_surat_kampus | 
    self.driver.find_element(By.ID, "no_surat_kampus").click()
    # 21 | type | id=no_surat_kampus | SK001-23fjoqw1
    self.driver.find_element(By.ID, "no_surat_kampus").send_keys("SK001-23fjoqw1")
    # 22 | click | id=tanggal_surat_kampus | 
    self.driver.find_element(By.ID, "tanggal_surat_kampus").click()
    # 23 | type | id=tanggal_surat_kampus | 2023-09-10
    self.driver.find_element(By.ID, "tanggal_surat_kampus").send_keys("2023-09-10")
    # 24 | click | id=judul_penelitian | 
    self.driver.find_element(By.ID, "judul_penelitian").click()
    # 25 | type | id=judul_penelitian | Pengaruh budidaya ikan
    self.driver.find_element(By.ID, "judul_penelitian").send_keys("Pengaruh budidaya ikan")
    # 26 | click | id=no_hp | 
    self.driver.find_element(By.ID, "no_hp").click()
    # 27 | type | id=no_hp | 09812327871238
    self.driver.find_element(By.ID, "no_hp").send_keys("09812327871238")
    # 28 | click | id=attach_ktp | 
    self.driver.find_element(By.ID, "attach_ktp").click()
    # 29 | type | id=attach_ktp | D:\TestUpload\catatan.txt
    self.driver.find_element(By.ID, "attach_ktp").send_keys("D:\\TestUpload\\catatan.txt")
    # 30 | click | id=attach_suratKampus | 
    self.driver.find_element(By.ID, "attach_suratKampus").click()
    # 31 | type | id=attach_suratKampus | D:\TestUpload\catatan.txt
    self.driver.find_element(By.ID, "attach_suratKampus").send_keys("D:\\TestUpload\\catatan.txt")
    # 32 | click | id=attach_ktm | 
    self.driver.find_element(By.ID, "attach_ktm").click()
    # 33 | type | id=attach_ktm | D:\TestUpload\catatan.txt
    self.driver.find_element(By.ID, "attach_ktm").send_keys("D:\\TestUpload\\catatan.txt")
    # 34 | click | id=attach_vaksin | 
    self.driver.find_element(By.ID, "attach_vaksin").click()
    # 35 | type | id=attach_vaksin | D:\TestUpload\catatan.txt
    self.driver.find_element(By.ID, "attach_vaksin").send_keys("D:\\TestUpload\\catatan.txt")
    # 36 | click | id=attach_pasFoto | 
    self.driver.find_element(By.ID, "attach_pasFoto").click()
    # 37 | type | id=attach_pasFoto | D:\TestUpload\catatan.txt
    self.driver.find_element(By.ID, "attach_pasFoto").send_keys("D:\\TestUpload\\catatan.txt")
    # 38 | click | id=attach_proposal | 
    self.driver.find_element(By.ID, "attach_proposal").click()
    # 39 | type | id=attach_proposal | D:\TestUpload\catatan.txt
    self.driver.find_element(By.ID, "attach_proposal").send_keys("D:\\TestUpload\\catatan.txt")
    # 40 | click | id=tombolKirim | 
    self.driver.find_element(By.ID, "tombolKirim").click()
    # 41 | mouseOver | id=tombolKirim | 
    element = self.driver.find_element(By.ID, "tombolKirim")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 42 | mouseOut | id=tombolKirim | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 43 | verifyElementPresent | css=.chakra-alert__title | 
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".chakra-alert__title")
    assert len(elements) > 0
    # 44 | close |  | 
    self.driver.close()
  
